env:
    # OrangeFox Sync Repository
    FOX_SYNC: https://gitlab.com/OrangeFox/sync.git

    # Config
    CONFIG: config.sh

    # Telegram
    TG_CHAT_ID: -1001191341989
    TG_TOKEN: ENCRYPTED[409f0da637fa952eee66b811c7973d9accaaa82a2ea9685a5b6bb61e9c7d4179dc557b2815f40070cfa90746d331302c]

    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 20G

  Checks_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/DozNaka/android_device_samsung_a21s/OF/scripts/checks.sh)"

  Sync_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/DozNaka/android_device_samsung_a21s/OF/scripts/sync.sh)"

  Build_script:
      - bash -c "$(curl -sL https://raw.githubusercontent.com/DozNaka/android_device_samsung_a21s/OF/scripts/build.sh)"

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - bash -c "$(curl -sL https://raw.githubusercontent.com/DozNaka/android_device_samsung_a21s/OF/scripts/upload.sh)"

